apiVersion: v1
kind: Service
metadata:
  name: stremio
spec:
  selector:
    app: stremio
  ports:
    - name: http
      port: 11470
      targetPort: http
    - name: https
      port: 12470
      targetPort: https
