apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgDI341ZbLWefeFlDoX1zxPeVSdn1nZC3GtChX8Xe1n0d5S/vnDbcKf1qDm55J/hwMhjw4O9bVWRJfzTB154/4sgbT6XdzX8mapb8efyVtsEg76RoFbeSRa3yviQH86FVCNr/JTC+3UbIhFVCgQn/nv2OxP+VtvjF7PJdaHEiD+j5jZAmjIYfG2aE0gmgLwszY2TutxMBgUz9nA1YjXUwPc/zuCJOXDVxYaQyqvlSMvyA3p/2sAhyLX1wCOhIiv5eKF9TiUv36mubyr3qc+yE9HPYadtwpDVw1EquSLl6dQZSIT9kT+yFOS4vrIOxG56F3PRsT+1ExF26FN/041QdNhLmU3f4i11SEQURek3HmoKWqBZ3sAF1z/Nli6tW8HnVhVpJaTA4B8+Qkc8b09JEPkF2nwJwIwxsWB96fTGc+ctGRoIho83NQHCG7ZJTQ3hyCQKsltzuCwJwKCrpbOumfC5GIWeltmPGWtOe79+qO/BBt22t6mP9Dfvs+0iyPzyX2/VhtA2EpW+gGuTrwhg7kGHgbXSSryulptMy5lzPDkV9PrLwWwuvOFQNR6Xl6m6PHv732MRcHfn+5whDg1RwQyw7QQmrh6vh1e92tTA+3njbWxdM3+IlMGi13FgbLob6CTomW0E7EiG4a/zOq165GprDkZe+8HAxhR/pfUnoGig4p/mYlS/IEZ4PgmdO3MReXEHaKF9uBr3+X2QrJsLFvQl
    admin-user: AgCtaTp1IQFenP71ZE4Gk1K2VBW/PhBPXMSwDq0nLKj7wloZdfbxTZVtlVyPYY3yEVw3pkwYmkNs8WsOTOlYJkYqTMXvXHFCJIEH/wzeGAM0735+vOYJ0IEZfxv/ugzpBBt2pAf7SKse5WCuToObUN3eYVZ7/PUFM+RIVXChtVJXRFjN5K6Izcq67wi7smHpQWjzkcG2Iz4YBV7EBB9ZriasjZFiFM0/hZBHVkbqxTL/7HWeIQTIDSDX0VcUPy1aYscWj3Cb+rjjxKpPTnTryCS6QyG9/Qzhn9ANCNuncb5mN+qdjZVKrwr6KK4HpKd1JkdchrXOlrgKFGKAQc6f9dDY+af0sk3V+Cf6QXUDVHEYcMU90Za5Kbc8H2NW1RfGjlzL85KjLlMnH4X4KVJ5f9TmJTSk3olN3/0UIzz5vuK+Tye5+sCSZrxgVFsR/boVQp+785jzSum6NMUOBs9mYv0KyRpYhhfDMxJ/h/EI/hFGq/S5L/q4zWSM95tbSgoZK42zCl/FU/T4bF604J5Sm18B747Q6cRJwk5f3jIpHdMnvrGbrFHGKFhZs5gtf3iMrU3eYRKjO0l8L6FMcJyfv8hzI9OaNnY2voEGmuyFYiVr3gXKvJyuq6Mzu5/Xzic21K2YXc7gja1izAeBwklxcClbOmxN2ZLrnHnnlUJo1y0Rm+48RlImq0PmUVWUu+KSCWwdOAndBw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: grafana
    type: Opaque
