title: "Sirius"
subtitle: "Apps"
logo: "https://static.vecteezy.com/system/resources/previews/002/412/550/large_2x/premium-athena-the-goddess-black-icon-logo-illustration-design-vector.jpg" # Updated logo URL
columns: "3"
connectivityCheck: true
defaults:
  layout: columns
  colorTheme: auto
  target: "_blank"
theme: default

services:
  - name: "Sirius"
    icon: "fas fa-star"
    items:
      - name: "Expense Tracker"
        icon: "fas fa-wallet"
        subtitle: "Manage expenses with ease"
        url: "https://expense.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "Transmission"
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Transmission_Icon.svg/120px-Transmission_Icon.svg.png"
        subtitle: "Transmission Web Interface"
        url: "https://transmission.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "Feeder"
        logo: "https://img.icons8.com/?size=100&id=qpuOQzhOVZ0a&format=png&color=000000"
        subtitle: "Feeder"
        url: "https://feeder.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "n8n"
        logo: "https://avatars.githubusercontent.com/u/45487711?s=200&v=4"
        subtitle: "Workflow Automation"
        url: "https://n8n.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"

  - name: "Admin"
    icon: "fas fa-shield-alt"
    items:
      - name: "File Browser"
        logo: "https://avatars.githubusercontent.com/u/35781395?s=48&v=4"
        subtitle: "File Browser"
        url: "https://browse.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "Grafana"
        logo: "https://grafana.com/static/img/menu/grafana2.svg"
        subtitle: "Monitoring & Observability"
        url: "https://grafana.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "Prometheus"
        logo: "https://raw.githubusercontent.com/cncf/artwork/master/projects/prometheus/icon/color/prometheus-icon-color.png"
        subtitle: "Metrics & Monitoring"
        url: "https://prometheus.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "Weave GitOps"
        logo: "https://avatars.githubusercontent.com/u/9976052?s=200&v=4"
        subtitle: "GitOps Dashboard"
        url: "https://weave.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "Athena"
        logo: "https://avatars.githubusercontent.com/u/2678585?s=200&v=4"
        subtitle: "Proxmox UI"
        url: "https://athena.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "Kubernetes Dashboard"
        logo: "https://avatars.githubusercontent.com/u/13629408?s=200&v=4"
        subtitle: "K8s Dashboard"
        url: "https://dashboard.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"

  - name: "Search"
    icon: "fas fa-search"
    items:
      - name: "Audiobookbay"
        logo: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFwAAABcCAMAAADUMSJqAAAAnFBMVEX////ZAQIgf3vZAADTAAD67u7xxMTigIDjh4f89vb11tXdODjXAgOStbMegH4Je3f35OTuvbzXZGXga2vhkJDqzs7pq6vwy8ofgXn1+PgAeXLYR0jf6egAdnPlra3YQ0R6qKbP3dvD1dPjmJjnoJ+xy8g8iYXq8fAyjYhjn5uHsq1VlZOiwr9xpqFQkovaXl/dLy/TGRnVOjnacXBojmgBAAAFIElEQVRoge2ZaXOjOBCGQeA4eECyZ3OA1kqABEh8JZv5//9tu3VwOMIG7A+7VXlrZorC8NBqtVrdGsf50Y/+b0qSqqqS5PrgKiuit5gIRt7ei3x9vS9UxaYkXDBKCSGUMsZJmRbra6DzFO0lAI4JKsYPxIzR7a66jJzsJFlBKZiOfxSfxIJsLjA/2TFN7hFn6VR8XgraYTHCul+jcCuaMrlVKmhcY5kQ5fYdtYXJ5czAY8IO2Wh2VjKCcLCdCbLdZZWxMKnWRVpKfowBBMaPZO9EPXC2zy0jX0dEUO019j7KNZFi05jTfp/mW67xrBwelUnKJJkKsjtpU7Zlkh6zcnDUbCQbDNqcHW5BmbZ9ID1Sz/NySBgkezbGMzsmI5CnA/1YSHpMtwNmNRMx+lEMj69ML9fzb1SlDBOxG8yGsCxlUhPFuQeVC0exwSIqFzM940jlQDZ2zWUlupLtTz6UlJhTxWYkG+gY8JTkp56BKAT4YUKi28mNqjzxZoJLh7JJOfodt6tTcxqJePRkGlWYL+Ky9/dEzuZhEhsdg2HW6/UCc6EYn/u1Spl9+35Ft7HtVLayjffEesUuMlyZznumtOAYhpYf5h+/pT4enIW+/P0RfH9Obl89I9/DQrB++JcnFXpz58bT8mffn4OhU8qtoZ7ITcXmsmdXa+48+qEnL21wOWnc6tc1lml1dljevSjdBc5nqK0Fy0N1jfCXO62VeSkXhNozbw7bLa8XUHv8qyelh3tn+aCvnwLH10+E88YvUKemNnjRGdONFyoB/OlB6xHgWq8Id3EMrlfDnUNf4sWts0k8KzQpDKVzP5Un0MQb30Wfh3jbxyv421gODCh0LKmpgszQiqPla2Pilx6/i/DGW69aLzfN6IV9RgFOWv4K7hdaEIquHL2PcBMsAH80WtZvZTijFvga136TEBe+G/ogNHFmBAsH/kHNIBL/8bXmbYgdLjpb7AL8jX5G5348K329Oouvv5WeZ84vX0W/d1u/lZQnLM9bcER7cvyfJiylW2qfu81UtOG27ARrqJ2Ng8d7qcd7XP7aRIC76hrhi3v9yPIsHCe0BV/Ob7W68LCB3+pH5qsO3OaW5NCBLzBRyXUedOE6zYQQ5+53t7yBb23JJeLdCfUU5wjutuDmdntCYRO27e+FaKUWgLsT4BVkVmthAnUNx2ooGgf3DHy3lovInrgwnx+gZGUduGeHe/43yyOoSWAz4/bKBGa63BBGx8FryyMu0k3cV1JFkNAhq42EN5ZDD4yNqZXtZKo5GwL3XIvlqkC2ulyuADIQ7rpWy0+VJtsp8CPLRU9RlIkrWE57avt3dZBwwYTK1thqemXOOS6D2+u5gl0D3lPnRtPgRxMK68S6+xN1BjEozvsttwbjmtNrWN6zh06EH1ves4dOi5Zjn9v3UDwxvEac27c5Ngn+LVq4Lefm/BqW2xsfjMXL4bBZ2Hei/RUsh2LW3v6PyYq9cJ5a2eYg57IJFX3nFgmeYxu4rMnxXQ3HshRbRbzowL0aTk8eRakjGQWHnhBbImV56Orm50bSPNO2yN6msbzfKagiJi3LVa8W1CW0321b6m6uhvP9yWOg3NQty1vTZUJ7/pcWtufmOnD+NLcVXKRnjpjWpaq4gqURfMi0R7PubaOZhp89+nMS9Qj4XHYlvr90Pl3VNEJPuFL9oR+2okW3iiP+/wVCUWEUXIaF/8cU/56Eq54obDVcAxWsjAKnvlw4M9vt5Xncj370o/+e/gVdSH1zDjc1IAAAAABJRU5ErkJggg=="
        subtitle: "Search audiobookbay"
        url: "https://abbsearch.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "YTS"
        logo: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Logo-YTS.svg"
        subtitle: "YTS search for movies"
        url: "https://ytssearch.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "Deaddrop"
        logo: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAhFBMVEX///8gICAAAAAdHR3V1dUMDAwGBgaqqqoVFRUbGxsYGBiNjY3g4OB7e3sSEhKSkpIsLCxdXV3z8/NLS0tubm6BgYGjo6PHx8ft7e22trb4+Ph1dXXn5+fBwcFVVVXb29vPz8+mpqYzMzObm5tmZmZCQkJZWVk2NjZGRkaGhoYmJiaxsbGgQVkrAAASH0lEQVR4nO1diZaiOhDViiCg4r5vtKJ22///f5PKAglEQBSn9XDfOfPahSQ3S22pxEajRo0aNWrUqFGjRo0aNWrUqFGjhobRZh8Ec/pfsN+s/ndjnovF/Gt6HoCOwfCnHSz+d9Mex2p+HCIf3yNNHcSz8IPhMfjfbXwArf4JwPKaWXBsgPGx9b+bWgbbNWXnZrKT8CjL3vx/N/g+BJSeX4idnLM+Jfk2Izk6ujfpEcSNz3y4zt5Bxu4nYKc5uL7NJOh1cBg02V+2n57CxIZe938TyEEwTg8fCpNTbzbfj6KvjfbbWe9CaabEkA/nvzxZg29INJlQlTCc3Wpza3am6zUx4g7s/irH7i7JzwfrJ09GznspoeTBcPOSFt+H1TrBz6XSMSj06JxKXn1ROjCttrUl0AYr0cbTb/GnV+0DONrzFiyra2wJbE6gTzQI711LwVAvgsDuD1mtM32COk0oIyu20NTG0YH201taDqMx6A3r+ddSBUEzsZbh/CcsgLm2glw4b7rQKVVSDxbdMajKwy81GZ6MjtYkGAT4Vrl2zWFG52pTnREEjs9t7v3Yqe1xsImNRtMuWRic8N+jNlUhfFpby2Ax8NX+HjK7rFtamU2Aic+FtrCty39cjF21t32pwY4QlCxvC0KH/qpr2/H/m4UTqEsQhrKrT1C2wBWcxV+afHZh/3hjy2CuNSLSXQtYly5yCNGMnCndR/6PSN0qBK1BPJHasC1d5q9iq3Wbih1YeuI/gL1CUBu1XelJSicnTJRXoVrF6024ftTDBFQbe/WQeB9r3aPMVPh6oNRyuEh/x9PlwPIhp+ALNH8yiLwq73zrkaqwkDPIuoy0D0J4RH1tErp0cZUK94G5Xw6/IJVE4gPYPVTuJclkbIuKysuvcgi5SoZe4v35gy7PMaUYhLzxX+3182qhn3y/96DQM/glU1YX8R8q924ErFZuaGvgxvMDaDZTb3V4Za81bDqWmWDL8N6dJUM6JtxHivZr/agBVVTeOP1+Bx61klsmj/BWddVhc6tT3cHDZZvmOZ8yo/QHlaGNDA3mcDcteu7G1CCrmJH/0vji0It08O9hPAwn6/4c23V8gjgImL5ZbPvryXA4PnA1iAz98j7L/cAKHWZ/tsCFcNkSdszltkhPRPcz9Le0GUat5ZmWzgTPOO7Sl4BPGtbVQPzYiFnAz81nVkQhtdplMFwrdt/JITYuv6NtXhZVYYrGIpOaTddTZEs7y43bw07K2W2mabdVFtzKId6lgVMFTeDHF3lRYGIF8egfY5+ociHbNTwCt1dWIWTrFNX/olLbQtMXGbqX8k2+D10QduIaNEtjlbJSdXx7TNd1wLo9mRGh2lHUesK5z+zgl7nBM5vb+kfQJfgSsjcLF2CjxdO3ckSGXs4XreWX+zIv0xdoYTRhReWNrv7CPGEHzKbrwyH7a4m5QC1vaDF/1H3U6C2IHcoZ95vWaU+0D2By4wmJq2CYZ38l1vPZIrC6YrdaLwmA/zBL35kOiPOtfTDPmaQYSeUMk15zEsuEXjh47qXHHNJXbGNI594hLhF6a7/HBrUG7rWZiWtTrMNm3he9i+ZgjIAQEQTP7cWHEQcRCRP5KEoBg21TIDwfKAMRw9wvuvEKxxq6cVzxYeclByMlvhfga5QJVKwGxM4eFg7JsABgIPTQBGdKHH523Wo3ai7RVgwPkg5xXcwbPbiVylWaIR1GrjWnTLAeI4p+pX5iGDWOVz9nPAOnWJubRDAs1h1N+4rre8aNinVEMceueAj9qBaLi0OCMb51wQFselJbXItlZdKlPkXBytXnONqqrC6DIV4MHrcQOzZ051ahAfSYWbnEts22jSaVStmZtQI2abVAxH7ifqnKydjEYtRaiTe8c6EBJDDUYrptIIddwSfPnohfLKIHSEUGqhv3IddWJ4+NTYFmHhYNIGoKChBobNxCs5vW4PBNi1Y8h6ox3+KlzrXuL5iblAb1Q1qg7VAd6fxuTJz8R0WNfPiXskbyeMAri6FYFqvCBNEnaIOeoAH0va/CJRCLP9WBVzCUwjosnshN7ZBeIlTcod5wq3gfWWLXIrSrZyjDMvPizcMQ0gHdhcWkh5iM0DjaKfO+QBHCwjk5VTOMQr43E9KT8B2MyjE7swc+QvyNETS/6FJ0hU+5YvVWyVDuKvSL9r//gxO0BWzc5ICsUNVscKqui1KUs5ztCVXKUMyWYyFLGx8IdtRG/8Jo7lTaBmw/YLikJsRkWbSnpCFTPcNAqahQyxZAhyzcKEPIY7utKdXhzqZwOaJrt5UzFIZJUV1BnAVutaD87cTmHXPV6XsejAozFK34rZyhDHddilnPzmRO3ZBRoPcJwfbOMVWvtStkFTU9GUNmgb5KGcq8lp9iHpPdPtJOQbtScwuZ3BhRO6B9LFZOFO9mxVTJEGtidnBBEQH7kMcd9GlNuIWzh15BvcotxZEQV5Uy/BHbSAVFBFD7jD2dEL5CNMKh4ILmuzW05rVfMUPcxNsH+NJwfisNcpFZYAkixGHvjqFRyOMnTOFv6WwYOhUzZLuGrM0Gz4A4lq2fSfOnInfhmBwq7mr0oauWQ3zLtpIHoXg5+G0MLLCdxCoZsnyBE06Zr5TOt62wMztOT8o5JliKHbeUu0sIvr2lX4jK8eDaO87662vaN2YifIFu4qBqq41Nlx8clpRn4Efx6I6k6MJmzZbhLL3aeKOh05LZeV4oPfflNUmRSavOMWpFlb4FNnhrx68VWGB/h2G4G1jy9em3cWXuuGHRcp/fGTfaFzHoDhnTx8cEDGPIKgxexnDD6moaWu06jsMPpnsAP10cPFxBbZPAZIM4wX/3U2A58cSLHtfh4g7JFq331QsYrtA3DBuZ3h2xYMyMnwBYcqZjkpfMEVtcucG5/IYsoYr9OsYQ2+IFDBcYRfSzFKIDdp/vLiz4NtONiA63cXciMaH7A8kTmspXaT8BuiTdFzCkbb9YvZveBSHOMAobikTDG96y2JfvRc3d7rwb8Tcc6NDaSflWLUNqZWIYyTwwDly/4+3NMQ+v3TTwRNBuFu8nApUzJp8Yh/sLrSOuoypl6B7okseB7KRNZh/CoDGNGHYC/v+U7I8GUYQ9t5GegX5jPjRwxA2PPVABx1d0xbG2VsfCTJO0TeOvcUX1JMNA7PRl2OjSn97LMD2b1qMwXTRKZLoQxcZCtQy98GRhTCLtIPLge8RQ7vMNbnuSntwnl2mHfOGmhRhL1R9aw7H7AoZNjx+wSLWCJ7rFDCVR/Yt6lDWZvSFEU8otZob6zPZEZ1XMkMtTPfxAbW4QO0JJho2TOobWVKXopTL9OcMt3vqirV4W2Ym3hipmyJLKWXVAVRhyA2/YWYq1lGKoiiQ6FmrPpJJwZR5767czxHItz6H/NkUU82UMWaInyg/YL752lNte3VrXGS4SR8A6jZ4yiChptI0yLVN/RHmez+0RhgGYTBrKyUvS6e7PQOTiSdfOfMpDZzhXjtc0meZWLQVmAqpfN56RppqXh4dmttaC5+NbdKFI+NgCMaV+6AxxGsZWKZtdsZ/BjBptopoY7sEVWkUuRD8v5agsxGAQuU+2B8dL3+yhM/yhozSJ5iVbd3GUDoM+mxyG86nle7IjRQMeOlqVCW4y+VH62ujArutqa0spMYZz1XdiYx6LRDT+ltqE0xluvnZYwSkidPbkYxWBxzbVRfC7XC5/f7/mSqfqDNsdJY9KWGmRY4mEe9paVhmutu1fVr7SANbFFd4mwQ01w6EWFTrDLZKKRBQPJ8vYMJvufqB+Pec2Bj78FR7yYiY0uZVFKsZRZxjgK2miiDMhMkvNmaDhoJ1fkAxvLTQeDfu+8enD4PaXY84iXQXiD53hHsWgGLRo70GYtDikW10cR2N4IwWR91VlxxL4ejLrom20NnSGG9xmEpH76Emh19DM+9HP+sSz1HzboFiIVeUnLvXdJxVh/KbOkO3Xj+IQD8MiDmolzowq6/DLdESGB1crSzLlk81Ln5XYqmlYCbuUbVtcLdy+j1OYv2362h7jxL/JkI58kKqJz2/70SOABiwoRsIsjFOu+hNM/lyFWhJWkiEmiswm6/V6Ejd4y17TSTux9HNEmiztpm5nEDLKmYywQQ9y0sGuyRMSMe7BIVJbwkGTfAmGIWQo6DYkUil1bTEiCctX6hmHNedeEplQ9yhk4gdt/aIxOkPipHzSe+pYNxVoC6yE+5TUh98Qqt2nxl1JzpmGO6HtwigtpoOQnElJhlPr5tHIDSSPMqU0vjYFtABmlQwt2YzFN5hOc2svA8hwdY6QOLBoOskNO9lDqmtZKUPirEaIGTiG1icYOk6WBTJwdG/dYLVhLW1WXyJwUiFDarjxCzqJ6TSeznBtZarnFuicTHYp+qEczVcwdKwYtlGERAxx/gVgZ9vStAfYgQrx0mh5t8BWanWqZeis+zE6Ro0UMcQJ7Hs5l9OtfHZEU052s2+x6Si1ykh0RQwL3PUTMeygyeJnHzWkg+jg96U/VOAuOxnYejLDyMPLz5KXDNFzpQzzfLkJYzgTluY9DMtdXXgLch/eyT8ehwwxLWS8v4NhQMvtzgsxjJzNJ8fbJMX82+amEPIk4MYdDNm3F2GYf2PBRN5X8/RQRkQxs+TNbAxjJhiPmE1SmGGDj8j+BLt2pvN3LNSMcogoBuq782vyFwGErUwwFDAqzPAsthKXJFHeQVv5chE+fIWKEfLwgKLCF8NkYogtchdbzCC/uAUYsrDLd5Rendh4dSGMzdp9pQQjiq4jzf1+erdW+sdrzFc/+flxMarerB1dvNLYTW9L+tHRWHn6sbqzsiK06/AZtfRNud5CVwydJpx8Uogh8U9201oLEqYym1yZDLyKCUYU8Uh199t8MkssU9zGdZ1DoVl6wI1P4WJtTQzx2uSNOETeNFxOVQFF6Pwkcl8caRdLj2/qN61Tw7ZyGVqDxsFXH+M1pMrvT+EFBKMcE8vXq4dwK3rfFc7SxLHGmNSVyxC/cfLlWIuIPwTLIeirXFRZ8o7iO5BKo/EBJkxDiIwEHjOcgI3C9KsAQ/Thxxb/oogzMvG6WoaQEmXVE0xQjOg14hmMUmEN3L7bF2DIlM/OY20XmSlRAGo70UlmXIDzRMQUfZiosVkxgTvsKguhGAVD0+VK/L0JF75UDeICY1nc0WE8hu0wXpKvum5fdLQDE93A4luf7oEdExQxxzFvk8lK5u+F3JZHRU+1AM9PTCQwtE5SD77sZkGk6ECY9PBFoo/Fbs4QDPs8HmpqGn8vVHbcQGwPp4JzW8LyMSo8pp7EEmBoiGAIx4bNNMFwzhW56ZYAbjcM+WTlxprIFTbsbs3AeuB+4hJYGm8tU9W1YLhird2Y7j/iIyWSDlRz1Ohmr6Z5d8O8BEoek4z9M/08N0UcOBGhvxWG7nPDE8+FcjBGMmTCdkYMX+YuoRDGCsOqkmWeAiVLTzLk+Yqmm+rEzV/8hcrwJU0ti7WfZMhgvKZdu2qoryXZ/GHEF/RoDMHAcAWqXo8ZVn3FzqOIUi1VhhsTwxGoai9i+Pprre9ElPJsK1eMz8GQp7UAVStEDKu/COpRSMfRO8cqc2YbthA36rZbS6Q3O1V7f8/ARlzL4sFYDsfaNzKM9iG3J366i8DwD/0CUga2rvDy4MpH6eQaGYol90XE6TW4/vkZGkEG4QjAcYVulZEh5rWNOvKkml9ViLAajEIxLsSG6fwGwyYEa/ljZi5MXnkR8jMQDKRU9cHgD3FfKzptCpf/9EMrD6GthFNvMIw+/ls/I5fCsW3GPQzNJfyVlRmAEWpEPIdh01zC//qNoDRauReT5TE0geQkI78UuRRLMPxTBPMp3s/wjxHMpXg3wz9HMI/ivQz/IMEcincy/JMETRSVPfk0w2784ZsQTFMkg2AusE17wKut/HD+LgTTFP1i12/vnHchmKZoFzlGN7beh2Apiu9FsATFdyN4N8X3I3gnxXckeBfF9yR4B8V3JViY4vsSLEjxnQkWovjeBAtQfHeCuRTfn2AOxU8gmEnxMwhmUPwUgjcpfg7BGxQ/iaCR4mcRTFN0bO+zCObFUT+AYDbFjyCYRfFDCN6m+DEEb1H8IIJmih9F0Lyn8VEEDXsan0YwSfEDCeoUP5KgSvFDCcYUP5agpPjBBDnFjyaIFN3PJogUP5xgjRo1atSoUaNGjRo1atSoUaNGjRofi3+yb/NWUpnFfgAAAABJRU5ErkJggg=="
        subtitle: "Search deaddrop"
        url: "https://ddsearch.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"

  - name: "Media"
    icon: "fas fa-headphones"
    items:
      # - name: "Readarr"
      #   logo: "https://readarr.com/img/logo.png"
      #   subtitle: "Auto download books"
      #   url: "https://readarr.sirius.moonblade.work"
      #   type: Ping
      #   method: "HEAD"
      #   mode: "no-cors"

      - name: "Audiobookshelf"
        logo: "https://www.audiobookshelf.org/Logo.png"
        subtitle: "Audiobookshelf"
        url: "https://audiobook.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "Plex"
        logo: "https://static.cdnlogo.com/logos/p/96/plex.svg"
        subtitle: "Plex Media Server"
        url: "https://plex.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "Jellyfin"
        logo: "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/jellyfin-logo.png"
        subtitle: "Jellyfin server"
        url: "https://jellyfin.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      - name: "Jackett"
        logo: "https://avatars.githubusercontent.com/u/15383019?s=48&v=4"
        subtitle: "Manage indexers"
        url: "https://jackett.moonblade.work"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
      # - name: "Beets"
      #   logo: "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/beets-icon.png"
      #   subtitle: "Manage your audiobook library"
      #   url: "https://beets.moonblade.work"
      #   type: Ping
      #   method: "HEAD"
      #   mode: "no-cors"
      # - name: "Prowlarr"
      #   logo: "https://docs.linuxserver.io/assets/icon.svg"
      #   subtitle: "Manage your indexers"
      #   url: "https://prowlarr.sirius.moonblade.work"
      #   type: Ping
      #   method: "HEAD"
      #   mode: "no-cors"
      # - name: "Jackett"
      #   logo: "https://avatars.githubusercontent.com/u/15383019?s=48&v=4"
      #   subtitle: "Manage indexers"
      #   url: "https://jackett.sirius.moonblade.work"
      #   type: Ping
      #   method: "HEAD"
      #   mode: "no-cors"
      #
  - name: "Misc"
    icon: "fas fa-box"
    items:
      - name: "Blog"
        logo: "https://cdn.pixabay.com/photo/2022/01/16/16/44/blogger-logo-6942640_1280.png"
        subtitle: "Blog on github"
        url: "https://moonblade.github.io/blog"
        type: Ping
        method: "HEAD"
        mode: "no-cors"
  #
  #     - name: "Athena"
  #       logo: "https://avatars.githubusercontent.com/u/2678585?s=200&v=4"
  #       subtitle: "Proxmox UI"
  #       url: "https://athena.moonblade.work"
  #       type: Ping
  #       method: "HEAD"
  #       mode: "no-cors"
  #
  # - name: "Raspberry Pi"
  #   icon: "fas fa-microchip"
  #   items:
  #     - name: "Torrent"
  #       logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Transmission_Icon.svg/120px-Transmission_Icon.svg.png"
  #       subtitle: "Transmission Web Interface"
  #       url: "http://ubuntu.tailab18b.ts.net:9091/transmission/web/"
  #       type: Ping
  #       method: "HEAD"
  #       mode: "no-cors"
  #
