---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: arlie-bearer-token
  namespace: prometheus
spec:
  encryptedData:
    token: AgCBCl2xaQTqS3x5KdmR5gwkQK+D/y5pMrIibJKZNGik3+kscC/uf0KliuTrWTmoGQMQJMo9eNPoMPwi68n3OTAi/FfNrJ5yZl66Qdq5+cx/RoWgPozn1NhWtWn0cqekVKwgNmh9RdzhjJoMY77uZbOqDwoTmGIpNXJulBM828qR9ss+5+/FLbm81Ne3YArWUy2pkxCfA+muPfyCHStAkIyHHaROG7W51A8hHbkCwEvv1Rtqd7nH2rF+mUAaH4ZIPuv3NwZeOxKEm63d7ypoy3KPB+zyAuXM9pJVMfN4af3BJDO/XCvk8GN8vHTkzQWyJ/+ThxvbYKjp6z2JQP1ng3UdGa1GnhFrTnsnRRNlapAtvi6bsY2unlcNDi7BpkMV8B3xGXHeOT699i3vqQ22hy7WAOcUZSy7ZDkK5SNSsIMWmcDgh+RqeNIGvjOPa7FNDaPfPQuIvgRo+Is+sezOv1j4i4Rdf9kp9O5FwHa6dgNh7qdvYPwv9n5QcGpsd728U1iZSuJlvn8XCcsONIB5LVuAkbZnPSYp6rt8GyHTe7nExUbwBFMDqKcL/LiaVfzUk50V9i05RBwbrgH8byHbWuYpsKFCciaXh5LY7UkTkdxNdf9R9uiuKHYSoUnIe8uP2ganXeBYS4a/U+PlFYE+/RYP0yFHbvqeOQXSfetgCfrFbyQvUsUXrrru1IhXtZnigjzdIOu3qqyJydb/NBim+MYiJxN6YVyCML4Fy9n4bDnc8zCa5gQgtXg415P+R+sg+qy6PdseNy/97w==
  template:
    metadata:
      creationTimestamp: null
      name: arlie-bearer-token
      namespace: prometheus
    type: Opaque
