apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prometheus-auth
  namespace: prometheus
spec:
  encryptedData:
    web.yml: AgDNKfEcgWrrhMxcFHMWxhokmLy46Cq+itaranWmZA26KJzjB1wqwG/bWg4sQ6Gem4BWUFip/YtAuOlFMFWg4xYgmlk2NCrqTgqflbcJantnRGopQ5gjxe2aLZu07yB6tZLLjmZdkDfh6DxTRqHutjgO71JPfXoa+6+MrQ9NmOQuwx0PtC9LrDCCAHoyZ0F2HhRC4T4XZziEMRLjcJxXURN1MBjiFBFX5HtIEuEWyYkyLWyo3NpyoNd3jmwUzaxnAGeZimpoF775lOLQy/fZ142E1TLRL+gBXuh3jhZ2yD1tBucUK0WSGxIPUOnL9I2CwVycqFvfKcbEdWQTA2hziDaSRMUCYSPOuTFcQQiMt6QSeH4IcoSY3DZ75aglnmi81AoEZ/+u0uej91jON7X1Ck12iW5O7ziUJOTJnQUrMepN9s7pH+eQp254Mh8WM/BCFe8ex64NH08mUEgijKs82B+eirrCLWm6VSr4238ypB8x7QZbwCIHCCCvjl2lQc2nrU3b0pifonkUZAGcCpMBc7GgeZvSGuWa/baYOoLcqh8/NzD/jlZHhMOv5A+i5lgufWlY8pW088APhUGnsmB5yYL6Cybl5RNixRuzOUN0RfFY2IXuPfwB4O/E/IPl9ERdNypqzgW/SjhRiEzmXBb2vLlZa7MCJn2DW3lqNQ6jTYpGotevN0sm/rqAT3NsqQ5focnwQFX0ZmsIX5FXX8BAVPi/l2/bnjTJZVuysaTll302iPLKnFdndtcDpzXP
  template:
    metadata:
      creationTimestamp: null
      name: prometheus-auth
      namespace: prometheus
    type: Opaque
